apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: skylar-smith-skylar-smith-poi-map-app-dev
  annotations:
    argocd/app-name: skylar-smith-skylar-smith-poi-map-app-dev
    backstage.io/kubernetes-id: skylar-smith-skylar-smith-poi-map-app-dev
    backstage.io/kubernetes-namespace: skylar-smith
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=skylar-smith-skylar-smith-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23Janus2/skylar-smith-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/dev-pipelines/ns/skylar-smith/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/k8s/ns/skylar-smith/deployments/skylar-smith-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23blues.6mbu.p1.openshiftapps.com/#https://github.com/Summit23Janus2/skylar-smith-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://skylar-smith-poi-map-app-skylar-smith.apps.summit23blues.6mbu.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/skylar-smith"
  system: workshop-system-skylar-smith
  consumesApis:
    - gateway-api-skylar-smith
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-skylar-smith
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/skylar-smith"
